# Generated by Django 5.1.2 on 2024-10-17 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usersubscription',
            name='password',
        ),
        migrations.AlterField(
            model_name='usersubscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
